# Site settings

title: Jigesh Parekh # Title of your site
email: jparekh117@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     jetlifejig  # Replace this with your Twitter username
github_username:      jigesh-parekh  # Replace this with your GitHub username
linkedin_username:    jigeshparekh  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown
